server:
  port: 8080
spring:
  application:
    name: nacos-service-one
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.52.100:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
