spring:
  application:
    name: cosumer-one
  cloud:
    # nacos 相关配置
    nacos:
      discovery:
        server-addr: 192.168.52.100:8848
server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
